version: 2.1

executors:
  node-chrome-executor:
    docker:
      - image: cimg/node:20.11-browsers
    working_directory: ~/project
    environment:
      CHROME_BIN: /usr/bin/google-chrome
  
  node-chrome-alternative:
    docker:
      - image: cimg/node:20.11
    working_directory: ~/project
    environment:
      CHROME_BIN: /usr/bin/google-chrome

jobs:
  install-dependencies:
    executor: node-chrome-executor
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            node --version
            npm --version
            npm cache clean --force
            rm -rf node_modules package-lock.json
            npm ci
      - persist_to_workspace:
          root: ~/project
          paths:
            - node_modules

  run-tests:
    executor: node-chrome-executor
    steps:
      - checkout
      - attach_workspace:
          at: ~/project
      - run:
          name: Install Chrome Dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -y wget unzip
            # Check for different Chrome command names
            if command -v google-chrome &> /dev/null; then
              echo "Google Chrome found: $(google-chrome --version)"
            elif command -v chromium-browser &> /dev/null; then
              echo "Chromium found: $(chromium-browser --version)"
              sudo ln -sf /usr/bin/chromium-browser /usr/bin/google-chrome
            elif command -v chromium &> /dev/null; then
              echo "Chromium found: $(chromium --version)"
              sudo ln -sf /usr/bin/chromium /usr/bin/google-chrome
            else
              # Install Chrome if not found
              wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
              echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
              sudo apt-get update
              sudo apt-get install -y google-chrome-stable
            fi
            # Verify Chrome is available
            google-chrome --version
            # Test headless mode
            google-chrome --headless --disable-gpu --no-sandbox --disable-dev-shm-usage --version
      - run:
          name: Update npm and verify Node.js
          command: |
            node --version
            npm --version
            npm cache clean --force
      - run:
          name: Run WebDriverIO Tests
          command: npx wdio run wdio.conf.js
          no_output_timeout: 10m
      - run:
          name: Generate Allure Report
          command: |
            npm install -g allure-commandline || true
            allure generate allure-results --clean -o allure-report
      - store_artifacts:
          path: allure-report
          destination: allure-report
      - store_artifacts:
          path: test/screenshots
          destination: screenshots
      - store_artifacts:
          path: test/videos
          destination: videos
      - store_test_results:
          path: test-results

  run-specific-test:
    executor: node-chrome-executor
    parameters:
      test-file:
        type: string
        default: "user_registration"
    steps:
      - checkout
      - attach_workspace:
          at: ~/project
      - run:
          name: Install Chrome Dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -y wget unzip
            # Check for different Chrome command names
            if command -v google-chrome &> /dev/null; then
              echo "Google Chrome found: $(google-chrome --version)"
            elif command -v chromium-browser &> /dev/null; then
              echo "Chromium found: $(chromium-browser --version)"
              sudo ln -sf /usr/bin/chromium-browser /usr/bin/google-chrome
            elif command -v chromium &> /dev/null; then
              echo "Chromium found: $(chromium --version)"
              sudo ln -sf /usr/bin/chromium /usr/bin/google-chrome
            else
              # Install Chrome if not found
              wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
              echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
              sudo apt-get update
              sudo apt-get install -y google-chrome-stable
            fi
            google-chrome --version
      - run:
          name: Update npm and verify Node.js
          command: |
            node --version
            npm --version
            npm cache clean --force
      - run:
          name: Run Specific Test
          command: npx wdio run wdio.conf.js --spec test/specs/<< parameters.test-file >>.js
          no_output_timeout: 10m
      - run:
          name: Generate Allure Report
          command: |
            npm install -g allure-commandline || true
            allure generate allure-results --clean -o allure-report
      - store_artifacts:
          path: allure-report
          destination: allure-report
      - store_artifacts:
          path: test/screenshots
          destination: screenshots
      - store_artifacts:
          path: test/videos
          destination: videos

  run-tests-fallback:
    executor: node-chrome-alternative
    steps:
      - checkout
      - attach_workspace:
          at: ~/project
      - run:
          name: Install Chrome Dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -y wget unzip
            # Install Chrome
            wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
            echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
            sudo apt-get update
            sudo apt-get install -y google-chrome-stable
            google-chrome --version
      - run:
          name: Update npm and verify Node.js
          command: |
            node --version
            npm --version
            npm cache clean --force
      - run:
          name: Run WebDriverIO Tests
          command: npx wdio run wdio.conf.js
          no_output_timeout: 10m
      - store_artifacts:
          path: allure-report
          destination: allure-report
      - store_artifacts:
          path: test/screenshots
          destination: screenshots

workflows:
  version: 2
  
  # Daily regression tests
  daily-regression:
    triggers:
      - schedule:
          cron: "0 6 * * *"  # Every day at 6:00 AM UTC
          filters:
            branches:
              only:
                - main
    jobs:
      - install-dependencies
      - run-tests:
          requires:
            - install-dependencies
      - run-tests-fallback:
          requires:
            - install-dependencies
          filters:
            branches:
              only:
                - main

  # Manual test runs
  manual-tests:
    jobs:
      - install-dependencies
      - run-tests:
          requires:
            - install-dependencies
      - run-specific-test:
          requires:
            - install-dependencies
          filters:
            branches:
              only:
                - main
                - develop

  # Pull request tests
  pr-tests:
    jobs:
      - install-dependencies
      - run-tests:
          requires:
            - install-dependencies
          filters:
            branches:
              ignore:
                - main
                - develop
