version: 2.1

executors:
  node-executor:
    docker:
      - image: cimg/node:20.0
    working_directory: ~/project

jobs:
  regression-tests:
    executor: node-executor
    steps:
      - checkout

      - run:
          name: Install Dependencies
          command: npm ci

      - run:
          name: Run Regression Tests
          command: npx wdio run wdio.conf.js

      - run:
          name: Generate Allure Report
          command: |
            npm install -g allure-commandline || true
            allure generate allure-results --clean -o allure-report
            # You can archive allure-report later if needed

workflows:
  regression:
    triggers:
      - schedule:
          cron: "15 5 * * *"  # Every day at 5:15 AM UTC (adjust as needed)
          filters:
            branches:
              only:
                - main

    jobs:
      - regression-tests
